### ISSUE TITLE
How to have Bounceview work with custom onTouchListener?

### ISSUE THREAD

**Issue by DynamesC** [hariprasanths/Bounceview-Android#3]

**Comment by hariprasanths** [comment]
It's not possible to implement a custom onTouchListener to a view that also uses bounceview. This is because Bounceview overrides the onTouchListener of the view on which it is applied for implementing the animations. However, you can use a custom onClickListener. If you must have to implement a custom onTouchListener, you can import the library and change the onTouchListener inside the Bounceview class directly.

**Comment by DynamesC** [comment]
Thanks for your reply! Yes, after looking into your code I realized the cause of the problem, and have modified your onTouchListener in my project. The animation works like a charm.
